<?php 
	$this->set('body_class', 'static privacy-polity');
	$this->Html->addCrumb('Política de Privacidade', array('controller' => 'pages', 'action' => 'display', 'terms_of_use', 'admin' => 'false'));
?>

<fieldset>
<div>
<h2 style="text-align:center;">Termos e Condições Gerais de uso do site</h2>
Estes Termos e Condições Gerais aplicam-se ao uso dos serviços oferecidos pelo BAZZAPP PUBLICIDADE LTDA, empresa devidamente inscrita no CNPJ/MF sob o n° 12.735.131/0001-94, doravante nominada BazzApp, por meio dos sites www.bazzapp.com.<br/>
Qualquer pessoa, doravante nominada Usuário, que pretenda utilizar os serviços do BazzApp deverá aceitar os Termos e Condições Gerais e todas as demais políticas e princípios que o regem.<br/>
A ACEITAÇÃO DESTES TERMOS E CONDIÇÕES GERAIS É ABSOLUTAMENTE INDISPENSÁVEL À UTILIZAÇÃO DOS SITES E SERVIÇOS PRESTADOS PELO BAZZAPP<br/>
<br/>
O usuário deverá ler, certificar-se de haver entendido e aceitar todas as condições estabelecidas nos Termos e Condições Gerais e nas Políticas de Privacidade, assim como nos demais documentos incorporados aos mesmos por referência, antes de seu cadastro como Usuário do BazzApp.
<br/>
<br/>

<h3>01 - Objeto</h3>
Os serviços objeto dos presentes Termos e Condições Gerais consistem em (i) ofertar e hospedar espaços nos sites www.bazzapp.com para que os Usuários anunciem à venda seus próprios produtos e/ou serviços e (ii) viabilizar o contato direto entre Usuários anunciantes e Usuários interessados em adquirir os produtos e serviços anunciados, por meio da divulgação dos dados de contato de uma parte à outra. BazzApp, portanto, possibilita que os Usuários contatem-se e negociem entre si diretamente, sem intervir no contato, na negociação ou na efetivação dos negócios, não sendo, nesta qualidade, fornecedor de quaisquer produtos ou serviços anunciados por seus Usuários nos sites www.bazzapp.com.
<br/><br/>

<h3>02 - Capacidade para cadastrar-se</h3>
Os serviços do BazzApp estão disponíveis apenas para as pessoas que tenham capacidade legal para contratá-los. Não podem utilizá-los, assim, pessoas que não gozem dessa capacidade, inclusive menores de idade, ou pessoas que tenham sido inabilitadas do BazzApp, temporária ou definitivamente, ficando, desde já, o usuário advertido das sanções legais do Código Civil, notadamente, art. 166, I; 171, I e 180 da lei n° 10.406/02.<br/>
Também não é permitido que uma mesma pessoa tenha mais de um cadastro. Se o BazzApp detectar, através do sistema de verificação de dados, cadastros duplicados, irá inabilitar definitivamente todos os cadastros.<br/>
Pessoas Jurídicas poderão cadastrar-se por seus representantes legais.<br/>
<br/><br/>

<h3>03 - Cadastro</h3>
O cadastramento ao BazzApp é feito através das informações do usuário vindas de seu perfil na rede social Facebook.<br/>
Ao se cadastrar no BazzApp o Usuário poderá utilizar todos os serviços disponibilizados pelas empresas do grupo, declarando para tanto ter lido, compreendido e aceitado os respectivos Termos e Condições de uso de cada serviço que passam, por referência, a fazer parte integrante destes Termos e Condições.<br/>
BazzApp não se responsabiliza pela correção dos Dados Pessoais inseridos por seus Usuários. Os Usuários garantem e respondem, em qualquer caso, civil e criminalmente, pela veracidade, exatidão e autenticidade, dos Dados Pessoais cadastrados.<br/>
BazzApp se reserva o direito de utilizar todos os meios válidos e possíveis para identificar seus Usuários, bem como de solicitar dados adicionais e documentos que estime serem pertinentes a fim de conferir os Dados Pessoais informados.<br/>
Caso o BazzApp decida checar a veracidade dos dados cadastrais de um Usuário e se constate haver entre eles dados incorretos ou inverídicos, ou ainda caso o Usuário se furte ou se negue a enviar os documentos requeridos, o BazzApp poderá bloquear o cadastro para vendas, suspender temporariamente ou cancelar definitivamente o cadastro, sem prejuízo de outras medidas que entender necessárias e oportunas.<br/>
Havendo a aplicação de quaisquer das sanções acima referidas, automaticamente serão cancelados os anúncios do respectivo Usuário, não lhe assistindo, por essa razão, qualquer sorte de indenização ou ressarcimento.<br/>
O Usuário acessará sua conta de seu perfil do Facebook, com respectivos login e senha e compromete-se a não informar a terceiros esses dados, responsabilizando-se integralmente pelo uso que deles seja feito.<br/>
O Usuário compromete-se a notificar o BazzApp imediatamente, e através de meio seguro, a respeito de qualquer uso não autorizado de sua conta, bem como o acesso não autorizado por terceiros a mesma. O Usuário será o único responsável pelas operações efetuadas em sua conta, uma vez que o acesso a mesma só será possível mediante a aposição da senha, cujo conhecimento é exclusivo do Usuário.<br/>
Em nenhuma hipótese será permitida a cessão, venda, aluguel ou outra forma de transferência da conta (incluindo-se qualificações e reputação). Também não se permitirá a manutenção de mais de um cadastro por uma mesma pessoa, ou ainda a criação de novos cadastros por pessoas cujos cadastros originais tenham sido cancelados por infrações às políticas do BazzApp.<br/>
O BazzApp se reserva o direito de recusar qualquer solicitação de cadastro e de cancelar um cadastro previamente aceito, desde que em desacordo com as políticas e regras do presente termo.
<br/><br/>

<h3>04 - Modificações dos Termos e Condições Gerais</h3>
BazzApp poderá alterar, a qualquer tempo, estes Termos e Condições Gerais, visando seu aprimoramento e melhoria dos serviços prestados. Os novos Termos e Condições entrarão em vigor 10 dias após publicados no site. No prazo de 5 (cinco) dias contados a partir da publicação das modificações, o Usuário deverá comunicar-se por e-mail caso não concorde com os termos alterados com atendimento@bazzapp.com. Nesse caso, o vínculo contratual deixará de existir, desde que não haja contas ou dívidas em aberto. Não havendo manifestação no prazo estipulado, entender-se-á que o Usuário aceitou tacitamente os novos Termos e Condições e o contrato continuará vinculando as partes.<br/>
As alterações não vigorarão em relação a negociações e anúncios já iniciados ao tempo em que as mesmas alterações sejam publicadas. Para estes, os Termos e Condições Gerais de Uso valerão com a redação anterior.
<br/><br/>

<h3>05 - Produtos anunciados</h3><br/>
<h4>5.1 Anúncios/ ofertas</h4><br/>
O Usuário poderá oferecer à venda produtos ou serviços em suas respectivas categorias e subcategorias. Os anúncios podem conter gráficos, textos, descrições, fotos e outras informações relevantes do produto ou serviço oferecido, sempre que tal prática não viole nenhum dispositivo deste contrato ou das demais políticas do BazzApp. O produto ou serviço oferecido pelo Usuário vendedor deve ser descrito com clareza quanto a suas características relevantes. Presumir-se-á que, mediante a inclusão do anúncio no BazzApp, o Usuário manifesta a intenção e declara possuir o direito de vender o produto oferecido, ou que está facultado para tal por seu titular, além de dispor do produto para entrega imediata. Os anúncios devem conter, caso necessário, a descrição de todos os impostos incidentes sobre a transação em estrita observância à legislação tributária aplicável.<br/>
O Usuário declara, também, que ao publicar um anúncio possui em estoque produtos em quantidade suficiente para cumprimento de sua oferta.
O BazzApp poderá remover aqueles anúncios cujo preço final não esteja de acordo com os Termos e Condições, não seja suficientemente claro, ou que permita algum tipo de variação, para assim evitar confusões ou mal entendidos quanto ao preço final do produto.
Tendo em vista que o Usuário comprador recebe os dados de contato do Usuário anunciante (e vice-versa) após manifestar a intenção na compra do item anunciado, não é permitido inserir ou manter no próprio anúncio quaisquer dados pessoais para contato, tais como, e sem se limitar, a números de telefones, endereços de e-mails, ou páginas de internet que contenham os dados mencionados anteriormente.
Não é permitido fazer publicidade de outros meios de pagamentos que não sejam expressamente previstos pelo BazzApp, a fim de explicitar a clareza e lisura dos meios de pagamento oferecidos pelo BazzApp caso por estes optem as partes contratantes. Caso se infrinja qualquer das disposições previstas nesta cláusula, o BazzApp poderá editar, solicitar que o Usuário o edite, ou remover o respectivo anúncio, hipótese em que não haverá estorno ou devolução de quantias pagas ou a pagar relativas ao anúncio suprimido.<br/><br/>
<h4>5.2 Inclusão de imagens e fotografias</h4> <br/>
O Usuário pode incluir imagens e fotografias do produto oferecido sempre que as mesmas correspondam ao produto, com exceção dos casos que se tratarem de serviços e bens intangíveis que, por sua natureza, não permitam tal correspondência.
O BazzApp poderá retirar do site publicações que contenham imagens que não estejam de acordo com o Termos e Condições de Uso e demais políticas de utilização do site. As imagens e fotografias dos produtos anunciados na modalidade Diamante e Ouro deverão cumprir com alguns requisitos adicionais como condição para serem expostos na Página Principal dos sites www.bazzapp.com. <br/><br/>
<h4>5.3 Produtos Proibidos</h4><br/>
Poderão ser anunciados/ofertados aqueles produtos ou serviços cuja venda não esteja expressamente proibida pelos Termos e Condições Gerais e demais políticas do BazzApp, ou pela lei vigente.<br/>
Fica expressamente proibida a venda de armas de fogo, narcóticos, tóxicos e qualquer sorte de drogas ilegais, bem como medicamentos e qualquer tipo de drogas em geral ou produtos aos quais se atribua efeitos terapêuticos de qualquer natureza, propriedade roubada, órgãos humanos, animais, no todo ou em parte, afora os constantes de rol enunciativo publicado em Produtos Proibidos, moedas e cédulas falsificadas, serviços de câmbio não autorizado, exceto venda de moedas antigas, produtos de contrabando, produtos falsificados ou adulterados, pólvora ou material explosivo, ações de empresas negociadas em Bolsa de Valores, bilhetes de loteria, listas de correio ou bases de dados pessoais, serviços e/ou produtos relacionados a prostituição ou similares, material pornográfico, obsceno ou contrário a moral e os bons costumes (salvo os produtos que forem cadastrados na categoria Adultos), quaisquer produtos cuja venda é expressamente proibida pelas leis vigentes, cigarros e outros produtos derivados do tabaco e/ou que façam apologia ao hábito de fumar, produtos que promovam a violência e ou a discriminação baseada em questões de raça, sexo, religião, nacionalidade, orientação sexual ou de qualquer outro tipo.<br/>
Também está proibida a venda de CDs que contenham música em formato MP3, quando a mesma não está expressamente autorizada pelo artista ou gravadora proprietária dos direitos autorais, ou infrinja alguma legislação. Também não podem ser cadastrados produtos que violem leis de restrição à pirataria de informática, de proteção de software, direitos do autor, patentes, marcas, modelos e desenhos industriais, nem software para OEM (entende-se como software para OEM, a versão especial do software pré-instalada no disco rígido de computadores pessoais no momento da fabricação, ou quando este for agrupado ao hardware do computador), NFR, cópias e/ou arquivos de backup, licença, programas acadêmicos e/ou desenvolvidos para alguma entidade educacional, ou segredos industriais, ou produtos que exijam do Usuário vendedor direito de venda, ou que somente podem ser vendidos com participação ou autorização de terceiros, e bens embargados ou afetados por alguma restrição de qualquer espécie quanto ao seu uso, exploração ou transferência de domínio ou posse. Fica proibida, ainda, a venda de aparelhos ativos, eletroestimuladores, para utilização em educação física, embelezamento e correção estética, que não estejam devidamente registrados perante a Agência Nacional de Vigilância Sanitária. É responsabilidade exclusiva do Usuário vendedor velar pela legalidade da venda de seus produtos e serviços e o BazzApp não assume nenhuma responsabilidade pela existência deles no site ou por negociações que não cumpram com as restrições descritas nos Termos e Condições Gerais. Para obter mais informações sobre produtos e serviços proibidos, consulte as Políticas sobre publicação de produtos e serviços no BazzApp.<br/>
Se você considera que algum anúncio infringe essa norma, pode denunciá-lo no link 'Denunciar', abaixo dos dados do vendedor.<br/><br/>

<h4>5.4. Proteção à Propriedade Intelectual</h4> <br/>
Suspeitando o BazzApp que tenha sido cometida alguma atividade ilícita ou que infrinja as normas aqui mencionados, alguns dados dos Usuários infratores poderão ser encaminhados aos membros do PPPI, conforme descrito no item Privacidade da Informação.<br/><br/>

<h4>5.5. Meios de Pagamento</h4><br/>
Ao anunciar um produto, o Usuário deve estar de acordo com a Aceitação da Plataforma PayPal, que permite o gerenciamento e a efetivação de pagamentos, pelos Usuários compradores, por diversos meios, tais como cartão de crédito, boleto bancário, transferência bancária online ou envio de dinheiro disponível em conta gráfica, considerando todas as regras e limitações do referido serviço, que podem ser verificados nos Termos e Condições Gerais de uso. Para tanto, o usuário declara ter lido, compreendido e aceitado os Termos e Condições de uso do PayPal.<br/>
O Usuário vendedor obriga-se ainda a não modificar o preço de venda do bem ou serviço por ele anunciado se o comprador decidir utilizar o PayPal.<br/>
É proibido o anúncio de outros meios de pagamento além dos enunciados pelo BazzApp constantes da plataforma PayPal na página de cadastramento de anúncios, ressalvada a livre opção do usuário comprador.<br/>
Caso o Usuário anunciante infrinja essa norma, o BazzApp poderá editar o espaço ou suprimir o respectivo anúncio,hipótese em que não haverá estorno das quantias pagas ou faturadas para tal anúncio.<br/><br/>

<h3>06 - Privacidade da Informação</h3>
Toda informação ou dado pessoal prestado pelo Usuário do BazzApp é armazenada em servidores ou meios magnéticos de alta segurança. BazzApp tomará todas as medidas possíveis para manter a confidencialidade e a segurança descritas nesta cláusula, porém não responderá por prejuízo que possa ser derivado da violação dessas medidas por parte de terceiros que utilizem as redes públicas ou a internet, subvertendo os sistemas de segurança para acessar as informações de Usuários.<br/><br/>

O Usuário expressamente autoriza que suas informações e dados pessoais sejam compartilhados pelo BazzApp com as demais empresas integrantes do grupo econômico.
<br/><br/>

<h3>07 - Obrigações dos Usuários</h3><br/>
7.1 Comprador. Os Usuários interessados em comprar produtos ou contratar serviços anunciados por vendedores no BazzApp devem manifestar seu interesse e realizar suas ofertas durante o prazo da negociação por estes estipulado. Os anúncios encerram-se quando expirado o prazo definido pelos Usuários vendedores ou quando acabam as quantidades nele contidas, e os anúncios de serviços expiram quando termina o prazo do anúncio determinado pelo Usuário anunciante. O Usuário comprador, após manifestar interesse na compra de um item anunciado, através das ferramentas do site, obriga-se a contatar o Usuário vendedor e efetivar a transação, salvo se a negociação for proibida por lei ou por estes Termos e Condições Gerais e anexos, ou na hipótese de os Usuários vendedor e comprador desistirem do negócio de comum acordo.<br/>
O BazzApp se reserva ainda o direito de estabelecer outras regras e procedimentos adicionais para que novos Usuários, Usuários "sem reputação" ou "com reputação negativa" (de acordo com os "medidores de reputação" utilizados pelo BazzApp) possam comprar um produto ou contratar um serviço anunciado por um vendedor. Estas condições poderão incluir serviços oferecidos por terceiros, importando eventualmente no pagamento de tarifas por utilização destes serviços.<br/>
Ao manifestar o interesse em algum produto, o Usuário comprador obriga-se a atender às condições de venda descritas no anúncio.<br/>
As ofertas só terão validade se realizadas por meio do sistema do BazzApp.<br/>
Tributos: O BazzApp não se responsabiliza pelas obrigações tributárias que recaiam nas atividades dos usuários do site. Assim como estabelece a legislação pertinente em vigor, o comprador deverá exigir nota fiscal do vendedor em suas transações, a menos que o Usuário vendedor esteja realizando uma venda eventual e não se enquadre no conceito legal de comerciante/empresário quanto aos bens postos em negociação.<br/><br/>
7.2. Obrigações do Usuário vendedor. O Usuário vendedor deve ter capacidade legal para vender o produto ou prestar o serviço anunciado. O Usuário vendedor obriga-se a entrar em contato com o Usuário comprador para efetivar a transação sempre que tenha recebido uma manifestação de interesse na compra do item anunciado. Apenas nos seguintes casos excepcionais o Usuário vendedor poderá não efetivar a venda: se não houve acordo com o Usuário comprador sobre a forma de pagamento ou prazo de entrega; se não foi possível verificar a verdadeira identidade ou as informações do Usuário comprador; se houve evidente erro de digitação ao cadastrar preço ou quantidade do produto anunciado.<br/>
Quando uma negociação se concretizar, o Usuário vendedor deverá, sempre que e conforme previsto, pagar ao BazzApp, em contrapartida aos serviços descritos na cláusula 1, o valor correspondente a um percentual do preço anunciado de 8,5%. Tal valor deverá ser pago também nos casos em que a negociação não se concretizar por responsabilidade do Usuário vendedor.<br/>
Em virtude de o BazzApp não figurar como parte nas transações de compra e venda de serviços e produtos que se realizam entre os Usuários, a responsabilidade por todas as obrigações delas decorrentes, sejam fiscais, trabalhistas, consumeristas ou de qualquer outra natureza, será exclusivamente do Usuário vendedor. Em caso de interpelação judicial que tenha como Réu oBazzApp, cujos fatos fundem-se em ações do Usuário vendedor, este será chamado ao processo devendo arcar com todos os ônus que daí decorram, nos termos do artigo 70, III do Código de Processo Civil. Por não figurar como parte nas transações de compra e venda que se realizam entre os Usuários, o BazzApp também não pode obrigar o Usuário vendedor a honrar sua obrigação ou efetivar a negociação.<br/>
Quando o vendedor receber uma oferta de compra de um item anunciado, dando início a uma negociação, deverá qualificar a contraparte conforme o estabelecido na cláusula 15 destes Termos e Condições Gerais. Caso não o faça no prazo lá definido, ser-lhe-á cobrado em contrapartida aos serviços descritos na cláusula 1, o valor correspondente a um percentual do preço anunciado, sempre que e conforme previsto, como se a venda houvesse sido concretizada.<br />
<br/>
O vendedor deverá ter em mente que, na medida em que atue como um fornecedor de produtos e/ou serviços ou como alienante eventual, sua oferta o vincula, nos termos do artigo 30 do Código de Defesa do Consumidor e do artigo 429 do Código Civil, cujo cumprimento pode ser exigido judicialmente pelo Usuário comprador.<br/>
Tributos: o BazzApp não se responsabiliza pelas obrigações de natureza tributária que incidam sobre os negócios realizados entre Usuário comprador e Usuário vendedor. Assim, o Usuário vendedor que atue como comerciante, nos termos da lei em vigor, responsabilizar-se-á pela integralidade das obrigações oriundas de suas atividades, notadamente pelos tributos incidentes.<br/>

<h3>08 - Práticas Vedadas</h3>
Os Usuários não poderão, entre outras atitudes previstas nestes Termos e Condições e seus anexos: a) manipular os preços dos produtos anunciados; b) interferir nas transações entre outros Usuários; c) manter algum tipo de comunicação direta, por e-mail ou por qualquer outra forma, salvo através da sessão de perguntas e respostas dos sites, com Usuário que potencialmente seja a sua contraparte em uma negociação, antes de manifestada a intenção na compra do respectivo item; d) divulgar dados pessoais de contato por qualquer meio, em qualquer espaço dos sites, antes de manifestada a intenção na compra do item anunciado; e) anunciar produtos proibidos pelas políticas do BazzApp e a lei; f) agredir, caluniar, injuriar ou difamar outros Usuários.
Estes tipos de comportamento poderão ser sancionados com a suspensão ou cancelamento do anúncio, ou com a suspensão ou cancelamento do seu cadastro como usuário do BazzApp, sem prejuízo das ações legais que possam ocorrer pela configuração de delitos ou contravenções ou os prejuízos civis que possam causar aos Usuários compradores.

<h3>09 - Violação no Sistema ou da Base de Dados</h3>
Não é permitida a utilização de nenhum dispositivo, software ou outro recurso que venha a interferir nas atividades e operações do BazzApp, bem como nos anúncios, descrições, contas ou seus bancos de dados. Qualquer intromissão, tentativa de, ou atividade que viole ou contrarie as leis de direito de propriedade intelectual e/ou as proibições estipuladas nestes Termos e Condições Gerais, tornarão o responsável passível das ações legais pertinentes, bem como das sanções aqui previstas, sendo ainda responsável pelas indenizações por eventuais danos causados.<br/><br/>

<h3>10 - Sanções</h3>
Sem prejuízo de outras medidas, o BazzApp poderá advertir, suspender ou cancelar, temporária ou definitivamente o cadastro de um usuário, seus anúncios ou aplicar uma sanção que impacte negativamente em sua reputação, a qualquer tempo, iniciando as ações legais cabíveis e/ou suspendendo a prestação de seus serviços se: <br />
a) o Usuário não cumprir qualquer dispositivo destesTermos e Condições Gerais e demais políticas do BazzApp; <br />
b) se descumprir com seus deveres de Usuário; c) se praticar atos fraudulentos ou dolosos; <br />
d) se não puder ser verificada a identidade do Usuário ou qualquer informação fornecida por ele esteja incorreta; <br/>
e) se o BazzApp entender que os anúncios ou qualquer atitude do Usuário tenham causado algum dano a terceiros ou ao próprio BazzApp ou tenham a potencialidade de assim o fazer. Nos casos de inabilitação do cadastro do Usuário, todos os anúncios ativos e/ou ofertas realizadas serão automaticamente cancelados e a informação de que o usuário não pertence mais à comunidade será incluída ao lado do nome de usuário. <br/>
O BazzApp reserva-se o direito de, a qualquer momento e a seu exclusivo critério, solicitar o envio de documentação pessoal e/ou exigir que um usuário torne-se Certificado.<br/><br/>

<h3>11 - Responsabilidades</h3>
O BazzApp se responsabiliza por eventuais danos causados aos seus usuários por defeitos ou vícios relativos exclusivamente à prestação do seu serviço de hospedagem e veiculação de anúncios nos sites www.bazzapp.com, desde que o BazzApp tenha dado causa aos referidos defeitos ou vícios. Esclareça-se, por oportuno, que o BazzApp não se responsabiliza por vícios ou defeitos técnicos e/ou operacionais oriundos do sistema do usuário ou de terceiros.
O BazzApp não é o proprietário dos produtos ou prestador dos serviços anunciados pelos Usuários nos sites www.bazzapp.com, não guarda a posse desses itens e não realiza as ofertas de venda. Tampouco intervém na entrega dos produtos ou na prestação dos serviços anunciados pelos Usuários nos sites www.bazzapp.com.
O BazzApp não se responsabiliza, por conseguinte, pela existência, quantidade, qualidade, estado, integridade ou legitimidade dos produtos oferecidos, adquiridos ou alienados pelos Usuários, assim como pela capacidade para contratar dos Usuários ou pela veracidade dos Dados Pessoais por eles inseridos em seus cadastros. O BazzApp não outorga garantia por vícios ocultos ou aparentes nas negociações entre os Usuários. Cada Usuário conhece e aceita ser o único responsável pelos produtos que anuncia ou pelas ofertas que realiza.<br/>
O BazzApp não será responsável pelo efetivo cumprimento das obrigações assumidas pelos Usuários. O Usuário reconhece e aceita que ao realizar negociações com outros Usuários ou terceiros faz por sua conta e risco, reconhecendo o BazzApp como mero fornecedor de serviços de disponibilização de espaço virtual para anúncio dos produtos e serviços ofertados por terceiros. Em nenhum caso o BazzApp será responsável pelo lucro cessante ou por qualquer outro dano e/ou prejuízo que o Usuário possa sofrer devido às negociações realizadas ou não realizadas através do BazzApp decorrentes da conduta de outros Usuários. <br/>
O BazzApp recomenda que toda transação seja realizada com cautela e bom senso. O Usuário deverá sopesar os riscos da negociação, levando em consideração que pode estar, eventualmente, lidando com menores de idade ou pessoas valendo-se de falsas identidades, ressalvada as responsabilidades daí decorrentes em virtude das normas legais já acima citadas.<br/>
O BazzApp responsabiliza-se por eventuais danos causados aos seus usuários por defeitos ou vícios relativos exclusivamente à prestação do seu serviço de hospedagem e veiculação de anúncios nos sites www.bazzapp.com, desde que o BazzApp tenha dado causa aos referidos defeitos ou vícios. Esclareça-se, por oportuno, que o BazzAppnão se responsabiliza por vícios ou defeitos técnicos e/ou operacionais oriundos do sistema do Usuário ou de terceiros.<br/>
Nos casos em que um ou mais Usuários ou algum terceiro inicie qualquer tipo de reclamação ou ação legal contra outro ou outros Usuários, todos e cada um dos Usuários envolvidos nas reclamações ou ações eximem de toda responsabilidade o BazzApp e os seus diretores, gerentes, empregados, agentes, operários, representantes e procuradores, observado, ainda, o estipulado na cláusula 7.<br/>
Uma vez que o Usuário vendedor tem a faculdade de eliminar, perguntar ou impedir outros Usuários de fazer perguntas ou ofertas de compra em seus anúncios, fica expressamente determinado que, caso exerça tal faculdade, se responsabilizará exclusivamente por esse ato e assumirá as conseqüências que dele possam advir, inclusive, ressalvando as responsabilidades decorrentes do art. 39, II da lei n° 8.078/90.<br/><br/>

<h3>12 - Alcance dos Serviços</h3>
Estes Termos e Condições Gerais não geram nenhum contrato de sociedade, de mandato, franquia ou relação de trabalho entre BazzApp e o Usuário. O Usuário manifesta ciência de queBazzApp não é parte de nenhuma transação realizada entre Usuários, nem possui controle algum sobre a qualidade, segurança ou legalidade dos produtos ou serviços anunciados pelos Usuários, sobre a veracidade ou exatidão dos anúncios elaborados pelos Usuários, e sobre a capacidade dos Usuários para negociar. O BazzApp não pode assegurar o êxito de qualquer transação realizada entre Usuários, tampouco verificar a identidade ou os dados pessoais dos usuários. O BazzApp não garante a veracidade da publicação de terceiros que apareça em seu site e não será responsável pela correspondência ou contratos que o Usuário realize com terceiros.<br/><br/>

<h3>13 - Falhas no Sistema</h3>
O BazzApp não se responsabiliza por qualquer dano, prejuízo ou perda sofridos pelo Usuário em razão de falhas na internet, no sistema ou no servidor utilizados pelo Usuário, decorrentes de condutas de terceiros, caso fortuito ou força maior. O BazzApp também não será responsável por qualquer vírus que possa atacar o equipamento do Usuário em decorrência do acesso, utilização ou navegação na internet ou como conseqüência da transferência de dados, arquivos, imagens, textos ou áudio.<br/><br/>

<h3>14 - Tarifas e Faturamento</h3>
O Cadastro no BazzApp é gratuito. Será cobrada uma tarifa de venda de 8,5%, que somente será paga ao BazzApp quando a negociação se concretizar, caso não se concretizar por culpa exclusiva do Usuário Vendedor, ou quando este não qualificar a negociação no prazo estipulado.<br/>
BazzApp se reserva o direito de modificar, aumentar ou eliminar tarifas vigentes a qualquer momento, sempre notificando os usuários na forma estipulada na cláusula 4 ou durante promoções e outras formas transitórias de alteração dos preços praticados. Tais alterações não vigorarão em relação a negociações e anúncios já iniciados ao tempo em que as mesmas alterações sejam publicadas. Para estes, os Termos e Condições Gerais de Uso valerão com a redação anterior.<br/>
BazzApp se reserva o direito de tomar as medidas judiciais e extrajudiciais pertinentes para receber os valores devidos. <br/><br/>

<h3>15 - Propriedade Intelectual e links</h3>
O uso comercial da expressão "BazzApp" como marca, nome empresarial ou nome de domínio, bem como os conteúdos das telas relativas aos serviços do BazzApp assim como os programas, bancos de dados, redes, arquivos que permitem que o Usuário acesse e use sua Conta são propriedade do BazzApp e estão protegidos pelas leis e tratados internacionais de direito autoral, marcas, patentes, modelos e desenhos industriais. O uso indevido e a reprodução total ou parcial dos referidos conteúdos são proibidos, salvo a autorização expressa do BazzApp. <br/><br/>

<h3>16 - Indenização</h3>
O Usuário indenizará BazzApp, suas filiais, empresas controladas ou controladoras, diretores, administradores, colaboradores, representantes e empregados por qualquer demanda promovida por outros usuários ou terceiros decorrentes de suas atividades no site ou por seu descumprimento dos Termos e Condições Gerais de Uso e demais políticas do BazzApp, ou pela violação de qualquer lei ou direitos de terceiros, incluindo honorários de advogados.<br/><br/>

<h3>18 - Legislação Aplicável e Foro de eleição</h3>
Todos os itens destes Termos e Condições Gerais de Uso são regidos pelas leis vigentes na República Federativa do Brasil. Para todos os assuntos referentes à interpretação, ao cumprimento ou qualquer outro questionamento relacionado a estes Termos e Condições Gerais de Uso, as partes concordam em se submeter ao Foro da Comarca de São Paulo, com exceção de reclamações apresentadas por Usuários que se enquadrem no conceito legal de consumidores, que poderão submeter tais reclamações ao foro de seu domicílio.<br/><br/>

</div>
</fieldset>	